### PR TITLE
Implement `with_shutdown` for default feature apps.

### PR DESCRIPTION
**Pull request by Grinkers**
I also would find a shutdown useful, especially for mocking tests. #108 seems to have gone stale, so I took a look at it.

A couple things to note:
1. The socket needs to be non-blocking, otherwise `for stream in socket.incoming() {` will end up blocking until a new connection comes in. We want to be able to shutdown even when there's not new connections coming in.
2. `app()` actually moves `self`, so run cannot be called again. So end-users would have to recreate a new App. This is useful because we don't need to ensure the App is restart-able.
3. I also went with an Arc<AtomicBool> because it makes it easier to send the signal to multiple apps (like in the shutdown example)

@w-henderson Any comments would be appreciated, I'm not too familiar with all the features/apps. I didn't tackle tokio because for some reason I'm having trouble with even `cargo build --features tokio` on master, which is likely a completely separate issue.

### CODE REVIEW

**Review by w-henderson — COMMENTED** [review]
I really would rather avoid polling even if it means something questionable like "connect once to ourselves to break out of the loop" or something like that.

Also, why have you chosen to include WebSocket in the shutdown example - isn't this overcomplicating the example a bit?

**Comment by Grinkers** [comment]
> I really would rather avoid polling even if it means something questionable like "connect once to ourselves to break out of the loop" or something like that.
> 
> Also, why have you chosen to include WebSocket in the shutdown example - isn't this overcomplicating the example a bit?

Connecting to ourselves to break out of the loop could work. I'll do that. It's a little hacky, but will have better idle performance.

I put the websocket app in the example to show how to shutdown with multiple apps running. It's similar to how I'm using Humphrey and was a "gotcha" for me. You initiate a shutdown, and it doesn't actually exit shutdown unless you send the signal to all the apps. The example would be greatly simplified if we don't want to show this case.

**Comment by Grinkers** [comment]
> > I really would rather avoid polling even if it means something questionable like "connect once to ourselves to break out of the loop" or something like that.
> > Also, why have you chosen to include WebSocket in the shutdown example - isn't this overcomplicating the example a bit?
> 
> Connecting to ourselves to break out of the loop could work. I'll do that. It's a little hacky, but will have better idle performance.
> 
> I put the websocket app in the example to show how to shutdown with multiple apps running. It's similar to how I'm using Humphrey and was a "gotcha" for me. You initiate a shutdown, and it doesn't actually exit shutdown unless you send the signal to all the apps. The example would be greatly simplified if we don't want to show this case.

Hm, it's a bit annoying to avoid all polling with only one shutdown signal between apps. Maybe an explicit signal for each app? It also fixes the overly complex example a bit too. I don't think it's an unreasonable expectation to shutdown multiple apps if you're running multiple apps?

**Comment by Grinkers** [comment]
Pushed an implementation that doesn't use any polling, only channels. Updated the example to be a very simple version of this. A separate thread waits on the signal, which sends it to the main run thread.

Lots of lines changed, but I recommend viewing the diff without whitespace changes.

**Comment by w-henderson** [comment]
This looks really good but it doesn't compile for me? Can you add a CI test for your new example too? Thanks.

**Comment by Grinkers** [comment]
> This looks really good but it doesn't compile for me? Can you add a CI test for your new example too? Thanks.

Added. 

I'll rebase after https://github.com/w-henderson/Humphrey/pull/109 is merged and mark this no longer WIP. I think there might be some resolver issues (I did this work based against #109, then rebased against master to make this PR to keep the diff clean).

**Comment by Grinkers** [comment]
@w-henderson 
just rebased, no other changes.

`cargo run --manifest-path examples/shutdown/Cargo.toml` works on a clean clone. 
https://github.com/Grinkers/Humphrey/actions/runs/7397166391/job/20123780698

Here's the CI run on my actions. Auth fails, but is out of scope of this PR. Removed "WIP" from the title.

**Comment by w-henderson** [comment]
Can you give it another quick rebase - I just fixed auth.

**Comment by Grinkers** [comment]
> Can you give it another quick rebase - I just fixed auth.

https://github.com/Grinkers/Humphrey/actions/runs/7397236476/job/20123983847
looks good.

**Comment by w-henderson** [comment]
The shutdown example doesn't work - I think if `addr` is `0.0.0.0:port` it can't connect to itself like that because that address is only valid for listening rather than connecting. It works if I use like `127.0.0.1:8000` but of course we need it to always work. I'm wondering if it's possible to bind the server such that it *isn't* accessible through `127.0.0.1:port` - if I'm right in thinking that's not the case then we can just connect to that instead of directly using `addr`. Can you look into it? Thanks.

**Comment by Grinkers** [comment]
> The shutdown example doesn't work - I think if `addr` is `0.0.0.0:port` it can't connect to itself like that because that address is only valid for listening rather than connecting. It works if I use like `127.0.0.1:8000` but of course we need it to always work. I'm wondering if it's possible to bind the server such that it _isn't_ accessible through `127.0.0.1:port` - if I'm right in thinking that's not the case then we can just connect to that instead of directly using `addr`. Can you look into it? Thanks.

Huh, weird. It works for me with both

```rust
app.run("0.0.0.0:8080").unwrap();
app.run("127.0.0.1:8080").unwrap();
 ```
 
 Sample size of one, but I'm on Fedora 39. What OS/networking setup are you testing on?

**Comment by w-henderson** [comment]
I'm testing on Windows - it seems a bit dodgy that Linux would automatically work with 0.0.0.0, I assume it just converts it to 127.0.0.1, which I guess is what we can do. Maybe have something that, if `addr`'s address is 0.0.0.0, connect to 127.0.0.1?

**Comment by Grinkers** [comment]
I was able to reproduce it on Windows. Something a bit weird going on for sure.

I've committed what I think is the correct thing to do, which is using the localhost loopback on the given port. I'm not a networking expert my any means, but I don't think this can fail. Tested it on windows on rustc 1.74.

**Review by w-henderson — CHANGES_REQUESTED** [review]
I think this is clearer, what do you think?

```rs
let mut local_addr = addr.to_socket_addrs().unwrap().next().unwrap();
if local_addr.ip().is_unspecified() {
    local_addr.set_ip(if local_addr.is_ipv4() {
        IpAddr::V4(Ipv4Addr::new(127, 0, 0, 1))
    } else {
        IpAddr::V6(Ipv6Addr::new(0, 0, 0, 0, 0, 0, 0, 0x1))
    });
}
```

**Comment by Grinkers** [comment]
I think your recommendation is correct. I moved it to a non-pub fn.

https://datatracker.ietf.org/doc/html/rfc4291#section-2.5.3
It seems like `localhost` can be wrong with some insane `hosts` file, for example. I wasn't sure about ipv6.

**Review by w-henderson — APPROVED** [review]
Okay, this looks good! Thank you for all your work on this, I'll merge it.

If you wouldn't mind having a look at implementing this for the Tokio feature too that would be awesome, it should be much easier with just the async `select!` macro choosing between servicing a new request and receiving a shutdown signal.

**Comment by Grinkers** [comment]
> Okay, this looks good! Thank you for all your work on this, I'll merge it.
> 
> If you wouldn't mind having a look at implementing this for the Tokio feature too that would be awesome, it should be much easier with just the async `select!` macro choosing between servicing a new request and receiving a shutdown signal.

Sure, I'll take a stab at it. I didn't before because 
`cargo build --features tokio` was failing to build. That might be something to look into, as a separate issue?

I'm able to run
`cargo run --manifest-path examples/stateful-tokio/Cargo.toml` so I have a good entry point. I'll open a new PR with shutdown. Probably not for a couple days.

**Comment by w-henderson** [comment]
`cargo build --features tokio` doesn't work in the workspace because Server and WS don't yet support the Tokio feature on the Core crate - it's something I should really do at some point but it'll be a massive job. Running `cargo build --features tokio` within the `humphrey` directory works.

**Comment by Grinkers** [comment]
> `cargo build --features tokio` doesn't work in the workspace because Server and WS don't yet support the Tokio feature on the Core crate - it's something I should really do at some point but it'll be a massive job. Running `cargo build --features tokio` within the `humphrey` directory works.

Understood. It was a scary output, so I previously didn't attempt looking at Tokio. Thanks for the great crate though! Otherwise it's been very easy to navigate and poke around.

**Pull request merged**
